### ISSUE TITLE
when compiling ｉt  encounter something wrong : “error: operands to ?: have different types”

### ISSUE THREAD

**Issue by fighterxi** [UM-ARM-Lab/sdf_tools#18]
Ｈｉ，
sorry to trouble you !
I have problems when compiling ｉｔ . The error message is　“...error: operands to ?: have different types...” .I use  ubuntu 14.04 , boost version is 1.54. I have tried to update gcc 4.84 to gcc 5.5  but this problem will still occured !  
The following is a detailed error message, 　looking  forward to your reply!

__________________________________________________

[ 89%] Built target sdf_tools_generate_messages
Scanning dependencies of target sdf_tools_gencpp
[ 89%] Built target sdf_tools_gencpp
Scanning dependencies of target sdf_tools
[ 90%] Building CXX object Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/collision_map.cpp.o
Linking CXX executable /home/relaybot/catkin_s0/devel/lib/bezier_planer/b_traj_server
[ 90%] Built target b_traj_server
[ 91%] Building CXX object Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/dynamic_spatial_hashed_collision_map.cpp.o
In file included from /home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/collision_map.hpp:14:0,
                 from /home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/src/sdf_tools/collision_map.cpp:15:
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp: In member function ‘double sdf_tools::SignedDistanceField::EstimateDistanceInternal(double, double, double, int64_t, int64_t, int64_t) const’:
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp:435:89: error: operands to ?: have different types ‘const Eigen::CwiseUnaryOp<Eigen::internal::scalar_opposite_op<double>, const Eigen::Matrix<double, 3, 1> >’ and ‘const Vector3d {aka const Eigen::Matrix<double, 3, 1>}’
 gen::Vector3d direction_to_boundary = (nominal_sdf_distance >= 0.0) ? -gradient
                                                                     ^
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp:435:89: note:   and each type can be converted to the other
Linking CXX executable /home/relaybot/catkin_s0/devel/lib/bezier_planer/random_forest_sensing
[ 91%] Built target random_forest_sensing
[ 92%] Building CXX object Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/sdf.cpp.o
In file included from /home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/collision_map.hpp:14:0,
                 from /home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/src/sdf_tools/dynamic_spatial_hashed_collision_map.cpp:15:
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp: In member function ‘double sdf_tools::SignedDistanceField::EstimateDistanceInternal(double, double, double, int64_t, int64_t, int64_t) const’:
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp:435:89: error: operands to ?: have different types ‘const Eigen::CwiseUnaryOp<Eigen::internal::scalar_opposite_op<double>, const Eigen::Matrix<double, 3, 1> >’ and ‘const Vector3d {aka const Eigen::Matrix<double, 3, 1>}’
             const Eigen::Vector3d direction_to_boundary = (nominal_sdf_distance >= 0.0) ? -gradient : gradient;
                                                                                         ^
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp:435:89: note:   and each type can be converted to the other
In file included from /home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/src/sdf_tools/sdf.cpp:14:0:
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp: In member function ‘double sdf_tools::SignedDistanceField::EstimateDistanceInternal(double, double, double, int64_t, int64_t, int64_t) const’:
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp:435:89: error: operands to ?: have different types ‘const Eigen::CwiseUnaryOp<Eigen::internal::scalar_opposite_op<double>, const Eigen::Matrix<double, 3, 1> >’ and ‘const Vector3d {aka const Eigen::Matrix<double, 3, 1>}’
             const Eigen::Vector3d direction_to_boundary = (nominal_sdf_distance >= 0.0) ? -gradient : gradient;
                                                                                         ^
/home/relaybot/catkin_s0/src/Btraj/third_party/sdf_tools/include/sdf_tools/sdf.hpp:435:89: note:   and each type can be converted to the other
make[2]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/collision_map.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/dynamic_spatial_hashed_collision_map.cpp.o] Error 1
make[2]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/src/sdf_tools/sdf.cpp.o] Error 1
make[1]: *** [Btraj/third_party/sdf_tools/CMakeFiles/sdf_tools.dir/all] Error 2
make: *** [all] Error 2
Invoking "make -j3 -l3" failed

**Comment by dmcconachie** [comment]
We have not tried compiling this library under Ubuntu 14.04 in quite some time, so I can't test any resolutions, but I can tell you exactly what the problem is, and give you several options to try to resolve the problem.

The problem is that Eigen and template meta-programming will often "delay" computation until an assignment happens. So `-gradient` is of type "`const Eigen::CwiseUnaryOp<...>`" while `gradient` is just a `const Eigen::Vector3d`. The `?` operator requires both sides of the `:` to be of the same type. On Ubuntu 16.04 with the default libraries, gcc manages to figure out that both of the expressions can be reduced to a `const Eigen::Vector3d` and everything works.

Here are a couple of potential resolutions:
- I am in the process of merging in a completely different way of doing EstimateDistance. You could take the branch I'm mergning in and use it directly. Hopefully it compiles on Ubuntu 14.04. We have not tested it on 14.04. https://github.com/calderpg/sdf_tools
- Replace the ternary operator with an if-else statement.
- Explicitly convert the `-gradient` into a `Eigen::Vector3d` The way I would do this would be:
```C++
const Eigen::Vector3d neg_gradient = -gradient;
onst Eigen::Vector3d direction_to_boundary = (nominal_sdf_distance >= 0.0) ? neg_gradient : gradient;
```
