### ISSUE TITLE
SDF.h not found

### ISSUE THREAD

**Issue by FaboNo** [UM-ARM-Lab/sdf_tools#23]
Dear All

When i tried to compile the project i got an error because the compiler cannot find SDH.h in 
sdf_tools/sdf.hpp

Thank you for your help

Regards

**Comment by dmcconachie** [comment]
`SDF.` is auto-generated as part of the build process. This requires that the package be part of a [catkin workspace](http://wiki.ros.org/catkin/Tutorials/create_a_workspace). 

(I'm assuming that you're using Ubuntu 16/18 or similar and thus no CMake/GCC problems could be interfering).

**Comment by FaboNo** [comment]
ah shame on me, I did not check that it was a msg.
but still I am not able to generate it (it does not appear in devel/include). I will investigate why
Thank you for your quick answer

**Comment by dmcconachie** [comment]
We have not tried this on Ubuntu 18 + ROS Melodic, so it's possible that there are some system changes that are interfering. I do know that this package compiles just fine with Ubuntu 16.04, ROS Kinetic, and GCC7.
