### ISSUE TITLE
How can I install "arc_utilities"

### ISSUE THREAD

**Issue by zengqingji** [UM-ARM-Lab/sdf_tools#29]
When i install this code to the workspace of ros, and run "catkin_make install"

`-- Could NOT find arc_utilities (missing: arc_utilities_DIR)
-- Could not find the required component 'arc_utilities'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "arc_utilities"
  with any of the following names:

    arc_utilitiesConfig.cmake
    arc_utilities-config.cmake

  Add the installation prefix of "arc_utilities" to CMAKE_PREFIX_PATH or set
  "arc_utilities_DIR" to a directory containing one of the above files.  If
  "arc_utilities" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  sdf_tools/CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/main/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/main/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed`

**Comment by PeterMitrano** [comment]
arc_utilities is here https://github.com/UM-ARM-Lab/arc_utilities, you should clone it into your workspace along side sdf_tools
